obs_dim: 64
history_len: 10
state_dim: 256
seq_length: 12
obs_feature_dim: [64, 128, 256, 512]
hist_feature_dim: [16, 32, 64]
state_feature_dim: [1024, 256, 256, 512]
cov_kernel_size: [7, 5, 3]
padding: [3, 2, 1]
pooling_size: 2
position_encoding: True
rate: [1, 0.5, 0.25]


# training parameters
batch_size: 16
learning_rate: 0.001
num_epochs: 50 # 10
decay_rate: 0.5
decay_step: 10 # 10
lamb: 0.5
nu: 0.05
